### ISSUE TITLE
MR19- Modelo UML (Opcional)

### ISSUE THREAD

**Issue by alvnavriv** [DP2-L1/ACME-L3-D01#27]

**Comment by jesmarver** [comment]
Entidad Auditor
- firm ->  Not blank, menos de 76 caracteres.
- proffesionalId -> Not blank, menos de 26 caracteres.
- List<Certifications> -> Not blank, menos de 101 caracteres.
- link -> String, opcional.


Relacionado con AbstractUserRole

**Comment by marsannar2** [comment]
Role Company

- name -> name (not blank, shorter than 76 characters)
- VAT number (not blank, shorter than 26 characters)
- summary (not blank, shorter than 101 characters)
- optional link with further information

**Comment by jesmarver** [comment]
Entidad Audit
- code -> regExp([A-Z]{1,3}[0-9][0-9]{3}), not blank, unique.
- conclusion -> not blank, menos de 101 caracteres.
- strongPoints -> not blank, menos de 101 caracteres.
- weakPoints -> not blank, menos de 101 caracteres.
- mark -> Double

**Comment by marsannar2** [comment]
Entidad Practicum

- a code (pattern “[A-Z]{1,3}[0-9][0-9]{3}”, not blank, unique)
- a title (not blank, shorter than 76 characters)
- an abstract (not blank, shorter than 101 characters)
- some goals (not blank, shorter than 101 characters)
- estimated total time (in hours, computed from the corresponding sessions plus/minus 10%)

**Comment by marsannar2** [comment]
Entidad Session

- a title (not blank, shorter than 76 characters)
- an abstract (not blank, shorter than 101 characters)
- a time period (at least one week ahead, at least one week long)
- optional link with further information

Esta entidad está relacionada con el practicum

**Comment by jesmarver** [comment]
Entidad AuditingRecords
- subject -> Not blank, menos de 76 caracteres.
- assessment -> Not blank, menos de 101 caracteres.
- period -> Al menos 1 hora.
- mark -> Enum(“A+”, “A”, “B”, “C”, “F”,“F-“).
- link -> Optional.

**Comment by marsannar2** [comment]
Entidad Dashboard

- total number of practica regarding theory or hands-on courses grouped by month during the last year
-  average, deviation, minimum, and maximum period length of the sessions in their practica
- average, deviation, minimum, and maximum period length of their practica

Esta entidad está relacionada con la entidad company y sessions

**Comment by jesmarver** [comment]
Entidad AuditorDashBoards
- audits -> Integer.
- averageAuditingRecord -> Double,
- deviationAuditingRecord -> Double.
- minimumAuditingRecord -> Integer.
- maximumAuditingRecord -> Integer.
- averageAuditingRecordTime -> Double,
- deviationAuditingRecordTime -> Double.
- minimumAuditingRecordTime -> Double.
- maximumAuditingRecordTime -> Double.
